# Generated by Django 5.1.2 on 2024-10-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('priority', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=15)),
                ('subtasks', models.JSONField(blank=True, default=list)),
                ('subtasks_done', models.JSONField(blank=True, default=list)),
                ('state', models.CharField(max_length=15)),
                ('assigned_to', models.ManyToManyField(related_name='task', to='api.contact')),
            ],
        ),
    ]
